test circleci

diff --git a/xcpEngine b/xcpEngine
--- a/xcpEngine
+++ b/xcpEngine
@@ -22,9 +22,6 @@
  PI:           Ted Satterthwaite
                sattertt@mail.med.upenn.edu
 
- What is XCP short for? Nobody knows what the X represents, but
- CP almost certainly stands for Communist Party.
-
  This program is free software: you can redistribute it and/or
  modify it under the terms of the GNU General Public License as
  published by the Free Software Foundation.
@@ -55,7 +52,6 @@
   * Other packages may be required for implementation of specific
     strategies, e.g. for denoising.
 
- XCP v0.6.0 ACCELERATOR
 
 XCPENGINE
 ###################################################################
@@ -171,9 +167,6 @@ done
 shift $((OPTIND-1))
 
 
-
-
-
 ###################################################################
 # Validate and parse the design and cohort files.
 # All pipeline variables are available after validation.
@@ -190,9 +183,15 @@ source ${XCPEDIR}/core/validateMode
 echo \
 "····································································"
 
-
-
-
+###################################################################
+# Check the inputs
+#source activate neuro
+#python ${XCPEDIR}/checks/check_inputs.py $@
+#if [ $? -eq 0 ]; then
+#    echo OK
+#else
+#    echo Your inputs would result in a failed pipeline. Exiting
+#fi
 
 ###################################################################
 # Obtain a timestamp for the current deployment of the engine.
