20170923: resolves #86

diff --git a/core/imgLocalise b/core/imgLocalise
--- a/core/imgLocalise
+++ b/core/imgLocalise
@@ -6,53 +6,94 @@
 ###################################################################
 
 ###################################################################
-# Convert the input image to a form suitable for processing by
-# the pipeline.
+# Convert all input images to a form suitable for processing by
+# the pipeline. First, obtain all images and pair each with an
+# import target path:
 ###################################################################
 img=${out[sub]}/${prefix[sub]}.nii.gz
-rm -f ${img}
+imgs="img[$sub]:${img[sub]}:${img}"
+###################################################################
+# Iterate over subject variables to determine whether any are
+# images. For each that is an image, pair it with an import path.
+###################################################################
+for v in "${cohort_vars[@]}"
+   do
+   vx=${v//\[${sub}\]}
+   if is_image ${!v}
+      then
+      tgt=${out[sub]}/import/${prefix[sub]}_${vx}.nii.gz
+      imgs="${imgs} ${v}:${!v}:${tgt}"
+      unset tgt
+   fi
+done
 
-###################################################################
-# Test #1:
-# Is the image formatted as a gzipped NIfTI?
-###################################################################
-contains ${img[sub]} '.nii.gz$'
-flag_imtype=$?
+for i in ${imgs}
+   do
+   unset nam ipt tgt
+   var=$(strslice ${i} 1 ':')
+   src=$(strslice ${i} 2 ':')
+   tgt=$(strslice ${i} 3 ':')
+   
+   ################################################################
+   # Test #1:
+   # Is the image formatted as a gzipped NIfTI?
+   ################################################################
+   contains ${src} '.nii.gz$'
+   flag_imtype=$?
 
-###################################################################
-# Test #2:
-# Is the image in RPI orientation?
-###################################################################
-[[ $($AFNI_PATH/@GetAfniOrient ${img[sub]}) == RPI ]]
-flag_orient=$?
+   ################################################################
+   # Test #2:
+   # Is the image in RPI orientation?
+   ################################################################
+   [[ $($AFNI_PATH/@GetAfniOrient ${src}) == RPI ]]
+   flag_orient=$?
+   
+   ################################################################
+   # For images other than the primary input, prepare an 'import'
+   # directory and reassign the input variable if either the image
+   # fails either test. If the image passes both tests, then do
+   # nothing.
+   ################################################################
+   if [[ ${tgt} != ${img} ]]; then
+   if [[ ${flag_imtype}${flag_orient} != 00 ]]
+      then
+      mkdir -p ${out[sub]}/import
+      eval ${var}=${tgt}
+   else
+      continue
+   fi
+   fi
+   rm -f ${tgt}
 
-###################################################################
-# Based on the outcomes of all tests, perform the appropriate
-# operation to localise the image.
-###################################################################
-case ${flag_imtype}${flag_orient} in
-   00)
-      ln -s ${img[sub]} ${img}
-      ;;
-   01)
-      $AFNI_PATH/3dresample \
-         -orient  RPI \
-         -inset   ${img[sub]} \
-         -prefix  ${img}
-      ;;
-   10)
-      $FSLDIR/bin/fslchfiletype NIFTI_GZ \
-         ${img[sub]} \
-         ${img}
-      ;;
-   11)
-      $FSLDIR/bin/fslchfiletype NIFTI_GZ \
-         ${img[sub]} \
-         ${img}
-      $AFNI_PATH/3dresample \
-         -overwrite \
-         -orient  RPI \
-         -inset   ${img} \
-         -prefix  ${img}
-      ;;
-esac
+   ################################################################
+   # Based on the outcomes of all tests, perform the appropriate
+   # operation to localise the image.
+   ################################################################
+   case ${flag_imtype}${flag_orient} in
+      00)
+         ln -sf ${src} ${tgt}
+         ;;
+      01)
+         $AFNI_PATH/3dresample \
+            -orient  RPI \
+            -inset   ${src} \
+            -prefix  ${tgt}
+         ;;
+      10)
+         $FSLDIR/bin/fslchfiletype NIFTI_GZ \
+            ${src} \
+            ${tgt}
+         ;;
+      11)
+         $FSLDIR/bin/fslchfiletype NIFTI_GZ \
+            ${src} \
+            ${tgt}
+         $AFNI_PATH/3dresample \
+            -overwrite \
+            -orient  RPI \
+            -inset   ${tgt} \
+            -prefix  ${tgt}
+         ;;
+   esac
+
+done
